name: gitactiondemo4
on:
  push:
      Branches:
           - main

jobs:
     jobs-demo:
      runs-on: ubuntu-latest

      steps:
       - name: Checkout repository
         uses: actions/checkout@v3


       - name: print message
         run: echo "welcome to maharashtra"
         
            