name: gitactiondemo4
on:
    push:
        Branches:
              - main

jobs:
     jobs-demo:
          runs-on: ubuntu-latest

          steps:
              - name: checkout code 
                uses: actoions/checkout@v2

              - name: print message
                 run: echo "welcome to maharashtra"
            